version: 2.1

orbs:
  python: circleci/python@2.1.1

executors:
  python:
    docker:
      - image: cimg/python:3.11.0

jobs:
  build_test:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: "flake8"
      - run:
          command: |
            pytest
          name: Test
      - run:
          command: |
            flake8
          name: Linting

  deploy:
    executor: python
    steps:
      - run:
          command: |
            echo TODO Deploy
          name: Deploy

  publish:
    executor: python
    steps:
      - run:
          command: |
              echo Ok
          name: Publish

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - deploy
          filters:
            branches:
              only: master
