version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

executors:
  python:
    docker:
      - image: cimg/python:3.11.0
    resource_class: small

jobs:
  build_test:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: "flake8"
      - run:
          command: |
            python manage.py migrate
            mv oc-lettings-site.sqlite3 oc-lettings-site.origin.sqlite3
            python manage.py migrate
            rm oc-lettings-site.sqlite3
            mv oc-lettings-site.origin.sqlite3 oc-lettings-site.sqlite3
          name: Migrations
      - run:
          command: |
            flake8
          name: Linting
      - run:
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
          name: Test
      - store_test_results:
          path: test-results

  containerize:
    executor: docker/docker
    steps:
      - checkout
      - docker/check:
          registry: docker.io
          use-docker-credentials-store: false
      - docker/build:
          image: meldsnake/oc-lettings-fr
          registry: docker.io
      - docker/push:
          image: meldsnake/oc-lettings-fr
          registry: docker.io
          tag: latest
      - docker/update-description:
          image: meldsnake/oc-lettings-fr
          registry: docker.io
  
  publish:
    executor: python
    steps:
        - checkout
        - heroku/install
        - heroku/deploy-via-git
        # - heroku/push-docker-image:
        #     process-types: web
        # - heroku/release-docker-image:
        #     process-types: web

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - containerize:
          requires:
            - build_test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - containerize
          filters:
            branches:
              only: master