version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0

executors:
  python:
    docker:
      - image: cimg/python:3.11.0
    resource_class: small

jobs:
  build_test:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: "flake8"
      - run:
          command: |
            flake8
          name: Linting
      - run:
          command: |
            pytest
          name: Test

  publish:
    executor: python
    steps:
      - run:
          command: |
              echo Ok
          name: Publish

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - docker/publish:
          deploy: true
          # Set Env variable DOCKER_LOGIN to the docker registry username
          # Set Env variable DOCKER_PASSWORD to the docker registry password, See personal access tokens.
          # Set the registry to use (default to docker.io)
          # registry: ${DOCKER_REGISTRY}
          image: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
          update-description: true
          tag: << pipeline.git.revision >>
          requires:
            - build_test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build_test
          filters:
            branches:
              only: master
